### ISSUE TITLE
git_pull文件太慢_建议把工程中图片删除

### ISSUE THREAD

**Issue by se7enXF** [mushroom-x/FGJumperMaster#3]
工程中加入图片不单单是题目中的问题,还会造成图片损坏.在廖的博客中提到,图片文件无法进行跟新检测,不适用于git仓库.

**Comment by mushroom-x** [comment]
添加样例图片是为了让使用者比较直观的看到每个文件夹中存放的是什么样的日志。 
出于用户友好考虑， 且后续无需更新
